application: aws-imoz-jp
version: master
runtime: go
api_version: go1
threadsafe: true
automatic_scaling:
  max_idle_instances: 1
  min_pending_latency: 5s

handlers:
- url: /.*
  script: _go_app
  login: admin

inbound_services:
- warmup

env_variables:
  AWS_REGION: 'ap-northeast-1'
